---
projects:
  EssentialsPE:
    path: EssentialsPE
    icon: EssentialsPE\resources\ess.jpg
    libs:
      - src: Falkirks/spoondetecctor/spoondetector
        version: ^0
  EssentialsPEconomy:
    path: EssentialsPEconomy
    icon: EssentialsPE\resources\ess.jpg
  EssentialsPEWarps:
    path: EssentialsPEWarps
    icon: EssentialsPE\resources\ess.jpg
  EssentialsPEHomes:
    path: EssentialsPEHomes
    icon: EssentialsPE\resources\ess.jpg
...
