---
name: EssentialsPE
main: EssentialsPE\Loader
version: 3.0.0
api:
- 3.0.0-ALPHA5
author: LegendsOfMCPE Team
website: https://github.com/LegendOfMCPE/EssentialsPE

# TODO: Permissions... Yay... Every command permission got changed.
...